- handle: data-layer
  dep: DATA_LAYER
  in_footer: false
  inline:
    path: config/integrations/scripts/data-layer.js
    position: before

- handle: google-optimize
  dep: GOOGLE_OPTIMIZE_ID
  localize:
    - GOOGLE_OPTIMIZE_ID
  in_footer: false
  inline:
    path: config/integrations/scripts/google-optimize.js
    position: before
  style:
    path: config/integrations/styles/google-optimize.css

- handle: google-analytics
  path: https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS }}
  dep: GOOGLE_ANALYTICS
  localize:
    - GOOGLE_OPTIMIZE_ID
    - GOOGLE_ANALYTICS
  in_footer: false
  inline:
    path: config/integrations/scripts/google-analytics.js
    position: after
  attrs:
    async: true

- handle: google-tag-manager
  dep: GOOGLE_TAG_MANAGER
  localize:
    - GOOGLE_TAG_MANAGER
    - GOOGLE_TAG_MANAGER_AUTH
    - GOOGLE_TAG_MANAGER_PREVIEW
    - GOOGLE_TAG_MANAGER_COOKIES
  in_footer: false
  inline:
    path: config/integrations/scripts/google-tag-manager.js
    position: before
  body_open:
    path: config/integrations/body/google-tag-manager.html

# - handle: google-recaptcha
#   path: https://www.google.com/recaptcha/api.js?onload=reCaptchaCallback&render=explicit
#   in_footer: false
#   attrs:
#     async: true

- handle: google-translate-element
  path: https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit
  in_footer: false
  inline:
    path: config/integrations/scripts/google-translate-element.js
    position: before
  style:
    path: config/integrations/styles/google-translate-element.css

- handle: ie11-custom-properties
  dep: SUPPORT_IE_11
  in_footer: false
  inline:
    path: config/integrations/scripts/ie11-custom-properties.js
    position: before

- handle: animate-on-scroll
  path: https://cdn.jsdelivr.net/gh/michalsnik/aos@v2.3.4/dist/aos.js
  in_footer: false
  inline:
    path: config/integrations/scripts/animate-on-scroll.js
    position: after
  style:
    path: config/integrations/styles/animate-on-scroll.css
